import Layout from "@/components/Layout";
import Image from "next/image";

export default function LandingPage() {
  const blogs = [
    {
      id: "1",
      title: "The New Autumn Denim Guide: The Best Gift For Stylish Women",
      category: "Coding",
      time: "June 06, 2022",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id urna et justo mattis tincidunt. Maecenas consectetur quam in nibh sollicitudin ultricies. Vestibulum ac nunc nunc. Pellentesque auctor massa ac leo mollis pretium a vel ligula. Sed gravida dictum massa, at rhoncus urna fringilla in. Duis orci nibh, iaculis nec finibus vitae, sagittis eget libero. Vestibulum sed placerat turpis. Nunc nec orci vel felis tempor rutrum aliquam eu orci. Proin euismod efficitur magna. Quisque pharetra purus tortor, laoreet pellentesque ligula blandit in. Pellentesque id commodo urna. Curabitur varius tellus nisl, non vestibulum odio tincidunt sed. Praesent non mauris a diam finibus porta. Mauris ac dapibus sapien. Maecenas imperdiet eros quis quam tempor, et tincidunt nibh suscipit. Praesent sit amet imperdiet est, eget pellentesque libero. Vestibulum in mollis ipsum, non ultricies ex. Vivamus porttitor sodales eros id gravida. Vestibulum ante orci, vulputate vitae tempus non, sollicitudin ut nibh. Mauris sed risus risus. Ut feugiat dui at lobortis molestie. Integer efficitur luctus ligula nec condimentum. Etiam ultrices, massa sed dignissim gravida, sapien neque cursus lectus, in tristique dui enim eu tellus. Aenean eu rhoncus felis, in commodo justo. Aenean vel diam faucibus, ornare libero eget, porttitor felis. Mauris eu sapien eros. Donec rhoncus molestie malesuada. Nullam ut lectus elit. Proin mollis turpis eu condimentum condimentum. Phasellus eget tincidunt arcu. Curabitur ornare semper dui. Fusce facilisis euismod enim ac ultrices. Mauris efficitur velit ac urna hendrerit, eu aliquet enim ullamcorper. Ut rhoncus volutpat tincidunt. Suspendisse non sapien sodales ipsum commodo congue at in nunc. Etiam ut metus a est malesuada lacinia vitae quis est. Quisque ullamcorper felis sit amet molestie consequat. In vel dapibus elit. Duis non neque in augue sagittis molestie Pellentesque felis lectus, tincidunt id diam quis, mollis tempor neque. Ut id pharetra nibh, a porta lacus. Nunc pretium sapien a arcu facilisis, tincidunt interdum nulla ullamcorper. Aliquam mattis ante nibh, at aliquet est dignissim et. Sed sit amet leo ut risus semper convallis. In aliquet nunc ac quam bibendum, et ultricies turpis imperdiet. Sed suscipit pellentesque facilisis. Sed ut consequat ante Suspendisse suscipit sodales metus. Mauris ac nisi sed ex malesuada tempus. Praesent sit amet congue nibh, eu molestie mauris. Ut ut viverra lorem. Donec pulvinar elit ut orci ultrices, id feugiat leo sollicitudin. Donec eleifend aliquam volutpat. Nulla ultrices nunc eu lectus blandit, sed tincidunt nulla porttitor. Quisque nec ornare erat. Aenean gravida nunc non facilisis molestie. Nam at est arcu. Suspendisse lobortis metus non nulla fermentum mollis. Proin ultrices mi lacus, a efficitur ipsum suscipit eget.",
      imageUrl: "/asset/image/sample/short4.jpg",
    },
    {
      id: "2",
      title: "Meet The Women Behind New York’s Coolest Design Shop",
      category: "Design",
      time: "June 09, 2022",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id urna et justo mattis tincidunt. Maecenas consectetur quam in nibh sollicitudin ultricies. Vestibulum ac nunc nunc. Pellentesque auctor massa ac leo mollis pretium a vel ligula. Sed gravida dictum massa, at rhoncus urna fringilla in. Duis orci nibh, iaculis nec finibus vitae, sagittis eget libero. Vestibulum sed placerat turpis. Nunc nec orci vel felis tempor rutrum aliquam eu orci. Proin euismod efficitur magna. Quisque pharetra purus tortor, laoreet pellentesque ligula blandit in. Pellentesque id commodo urna. Curabitur varius tellus nisl, non vestibulum odio tincidunt sed. Praesent non mauris a diam finibus porta. Mauris ac dapibus sapien. Maecenas imperdiet eros quis quam tempor, et tincidunt nibh suscipit. Praesent sit amet imperdiet est, eget pellentesque libero. Vestibulum in mollis ipsum, non ultricies ex. Vivamus porttitor sodales eros id gravida. Vestibulum ante orci, vulputate vitae tempus non, sollicitudin ut nibh. Mauris sed risus risus. Ut feugiat dui at lobortis molestie. Integer efficitur luctus ligula nec condimentum. Etiam ultrices, massa sed dignissim gravida, sapien neque cursus lectus, in tristique dui enim eu tellus. Aenean eu rhoncus felis, in commodo justo. Aenean vel diam faucibus, ornare libero eget, porttitor felis. Mauris eu sapien eros. Donec rhoncus molestie malesuada. Nullam ut lectus elit. Proin mollis turpis eu condimentum condimentum. Phasellus eget tincidunt arcu. Curabitur ornare semper dui. Fusce facilisis euismod enim ac ultrices. Mauris efficitur velit ac urna hendrerit, eu aliquet enim ullamcorper. Ut rhoncus volutpat tincidunt. Suspendisse non sapien sodales ipsum commodo congue at in nunc. Etiam ut metus a est malesuada lacinia vitae quis est. Quisque ullamcorper felis sit amet molestie consequat. In vel dapibus elit. Duis non neque in augue sagittis molestie Pellentesque felis lectus, tincidunt id diam quis, mollis tempor neque. Ut id pharetra nibh, a porta lacus. Nunc pretium sapien a arcu facilisis, tincidunt interdum nulla ullamcorper. Aliquam mattis ante nibh, at aliquet est dignissim et. Sed sit amet leo ut risus semper convallis. In aliquet nunc ac quam bibendum, et ultricies turpis imperdiet. Sed suscipit pellentesque facilisis. Sed ut consequat ante Suspendisse suscipit sodales metus. Mauris ac nisi sed ex malesuada tempus. Praesent sit amet congue nibh, eu molestie mauris. Ut ut viverra lorem. Donec pulvinar elit ut orci ultrices, id feugiat leo sollicitudin. Donec eleifend aliquam volutpat. Nulla ultrices nunc eu lectus blandit, sed tincidunt nulla porttitor. Quisque nec ornare erat. Aenean gravida nunc non facilisis molestie. Nam at est arcu. Suspendisse lobortis metus non nulla fermentum mollis. Proin ultrices mi lacus, a efficitur ipsum suscipit eget.",
      imageUrl: "/asset/image/sample/sample22.jpg",
    },
    {
      id: "3",
      title: "The New Autumn Denim Guide: The Best Gift For Stylish Women",
      category: "Coding",
      time: "June 06, 2022",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id urna et justo mattis tincidunt. Maecenas consectetur quam in nibh sollicitudin ultricies. Vestibulum ac nunc nunc. Pellentesque auctor massa ac leo mollis pretium a vel ligula. Sed gravida dictum massa, at rhoncus urna fringilla in. Duis orci nibh, iaculis nec finibus vitae, sagittis eget libero. Vestibulum sed placerat turpis. Nunc nec orci vel felis tempor rutrum aliquam eu orci. Proin euismod efficitur magna. Quisque pharetra purus tortor, laoreet pellentesque ligula blandit in. Pellentesque id commodo urna. Curabitur varius tellus nisl, non vestibulum odio tincidunt sed. Praesent non mauris a diam finibus porta. Mauris ac dapibus sapien. Maecenas imperdiet eros quis quam tempor, et tincidunt nibh suscipit. Praesent sit amet imperdiet est, eget pellentesque libero. Vestibulum in mollis ipsum, non ultricies ex. Vivamus porttitor sodales eros id gravida. Vestibulum ante orci, vulputate vitae tempus non, sollicitudin ut nibh. Mauris sed risus risus. Ut feugiat dui at lobortis molestie. Integer efficitur luctus ligula nec condimentum. Etiam ultrices, massa sed dignissim gravida, sapien neque cursus lectus, in tristique dui enim eu tellus. Aenean eu rhoncus felis, in commodo justo. Aenean vel diam faucibus, ornare libero eget, porttitor felis. Mauris eu sapien eros. Donec rhoncus molestie malesuada. Nullam ut lectus elit. Proin mollis turpis eu condimentum condimentum. Phasellus eget tincidunt arcu. Curabitur ornare semper dui. Fusce facilisis euismod enim ac ultrices. Mauris efficitur velit ac urna hendrerit, eu aliquet enim ullamcorper. Ut rhoncus volutpat tincidunt. Suspendisse non sapien sodales ipsum commodo congue at in nunc. Etiam ut metus a est malesuada lacinia vitae quis est. Quisque ullamcorper felis sit amet molestie consequat. In vel dapibus elit. Duis non neque in augue sagittis molestie Pellentesque felis lectus, tincidunt id diam quis, mollis tempor neque. Ut id pharetra nibh, a porta lacus. Nunc pretium sapien a arcu facilisis, tincidunt interdum nulla ullamcorper. Aliquam mattis ante nibh, at aliquet est dignissim et. Sed sit amet leo ut risus semper convallis. In aliquet nunc ac quam bibendum, et ultricies turpis imperdiet. Sed suscipit pellentesque facilisis. Sed ut consequat ante Suspendisse suscipit sodales metus. Mauris ac nisi sed ex malesuada tempus. Praesent sit amet congue nibh, eu molestie mauris. Ut ut viverra lorem. Donec pulvinar elit ut orci ultrices, id feugiat leo sollicitudin. Donec eleifend aliquam volutpat. Nulla ultrices nunc eu lectus blandit, sed tincidunt nulla porttitor. Quisque nec ornare erat. Aenean gravida nunc non facilisis molestie. Nam at est arcu. Suspendisse lobortis metus non nulla fermentum mollis. Proin ultrices mi lacus, a efficitur ipsum suscipit eget.",
      imageUrl: "/asset/image/sample/sample24.jpg",
    },
    {
      id: "4",
      title: "Meet The Women Behind New York’s Coolest Design Shop",
      category: "Design",
      time: "June 09, 2022",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id urna et justo mattis tincidunt. Maecenas consectetur quam in nibh sollicitudin ultricies. Vestibulum ac nunc nunc. Pellentesque auctor massa ac leo mollis pretium a vel ligula. Sed gravida dictum massa, at rhoncus urna fringilla in. Duis orci nibh, iaculis nec finibus vitae, sagittis eget libero. Vestibulum sed placerat turpis. Nunc nec orci vel felis tempor rutrum aliquam eu orci. Proin euismod efficitur magna. Quisque pharetra purus tortor, laoreet pellentesque ligula blandit in. Pellentesque id commodo urna. Curabitur varius tellus nisl, non vestibulum odio tincidunt sed. Praesent non mauris a diam finibus porta. Mauris ac dapibus sapien. Maecenas imperdiet eros quis quam tempor, et tincidunt nibh suscipit. Praesent sit amet imperdiet est, eget pellentesque libero. Vestibulum in mollis ipsum, non ultricies ex. Vivamus porttitor sodales eros id gravida. Vestibulum ante orci, vulputate vitae tempus non, sollicitudin ut nibh. Mauris sed risus risus. Ut feugiat dui at lobortis molestie. Integer efficitur luctus ligula nec condimentum. Etiam ultrices, massa sed dignissim gravida, sapien neque cursus lectus, in tristique dui enim eu tellus. Aenean eu rhoncus felis, in commodo justo. Aenean vel diam faucibus, ornare libero eget, porttitor felis. Mauris eu sapien eros. Donec rhoncus molestie malesuada. Nullam ut lectus elit. Proin mollis turpis eu condimentum condimentum. Phasellus eget tincidunt arcu. Curabitur ornare semper dui. Fusce facilisis euismod enim ac ultrices. Mauris efficitur velit ac urna hendrerit, eu aliquet enim ullamcorper. Ut rhoncus volutpat tincidunt. Suspendisse non sapien sodales ipsum commodo congue at in nunc. Etiam ut metus a est malesuada lacinia vitae quis est. Quisque ullamcorper felis sit amet molestie consequat. In vel dapibus elit. Duis non neque in augue sagittis molestie Pellentesque felis lectus, tincidunt id diam quis, mollis tempor neque. Ut id pharetra nibh, a porta lacus. Nunc pretium sapien a arcu facilisis, tincidunt interdum nulla ullamcorper. Aliquam mattis ante nibh, at aliquet est dignissim et. Sed sit amet leo ut risus semper convallis. In aliquet nunc ac quam bibendum, et ultricies turpis imperdiet. Sed suscipit pellentesque facilisis. Sed ut consequat ante Suspendisse suscipit sodales metus. Mauris ac nisi sed ex malesuada tempus. Praesent sit amet congue nibh, eu molestie mauris. Ut ut viverra lorem. Donec pulvinar elit ut orci ultrices, id feugiat leo sollicitudin. Donec eleifend aliquam volutpat. Nulla ultrices nunc eu lectus blandit, sed tincidunt nulla porttitor. Quisque nec ornare erat. Aenean gravida nunc non facilisis molestie. Nam at est arcu. Suspendisse lobortis metus non nulla fermentum mollis. Proin ultrices mi lacus, a efficitur ipsum suscipit eget.",
      imageUrl: "/asset/image/sample/sample6.jpg",
    },
    {
      id: "5",
      title: "The New Autumn Denim Guide: The Best Gift For Stylish Women",
      category: "Coding",
      time: "June 06, 2022",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id urna et justo mattis tincidunt. Maecenas consectetur quam in nibh sollicitudin ultricies. Vestibulum ac nunc nunc. Pellentesque auctor massa ac leo mollis pretium a vel ligula. Sed gravida dictum massa, at rhoncus urna fringilla in. Duis orci nibh, iaculis nec finibus vitae, sagittis eget libero. Vestibulum sed placerat turpis. Nunc nec orci vel felis tempor rutrum aliquam eu orci. Proin euismod efficitur magna. Quisque pharetra purus tortor, laoreet pellentesque ligula blandit in. Pellentesque id commodo urna. Curabitur varius tellus nisl, non vestibulum odio tincidunt sed. Praesent non mauris a diam finibus porta. Mauris ac dapibus sapien. Maecenas imperdiet eros quis quam tempor, et tincidunt nibh suscipit. Praesent sit amet imperdiet est, eget pellentesque libero. Vestibulum in mollis ipsum, non ultricies ex. Vivamus porttitor sodales eros id gravida. Vestibulum ante orci, vulputate vitae tempus non, sollicitudin ut nibh. Mauris sed risus risus. Ut feugiat dui at lobortis molestie. Integer efficitur luctus ligula nec condimentum. Etiam ultrices, massa sed dignissim gravida, sapien neque cursus lectus, in tristique dui enim eu tellus. Aenean eu rhoncus felis, in commodo justo. Aenean vel diam faucibus, ornare libero eget, porttitor felis. Mauris eu sapien eros. Donec rhoncus molestie malesuada. Nullam ut lectus elit. Proin mollis turpis eu condimentum condimentum. Phasellus eget tincidunt arcu. Curabitur ornare semper dui. Fusce facilisis euismod enim ac ultrices. Mauris efficitur velit ac urna hendrerit, eu aliquet enim ullamcorper. Ut rhoncus volutpat tincidunt. Suspendisse non sapien sodales ipsum commodo congue at in nunc. Etiam ut metus a est malesuada lacinia vitae quis est. Quisque ullamcorper felis sit amet molestie consequat. In vel dapibus elit. Duis non neque in augue sagittis molestie Pellentesque felis lectus, tincidunt id diam quis, mollis tempor neque. Ut id pharetra nibh, a porta lacus. Nunc pretium sapien a arcu facilisis, tincidunt interdum nulla ullamcorper. Aliquam mattis ante nibh, at aliquet est dignissim et. Sed sit amet leo ut risus semper convallis. In aliquet nunc ac quam bibendum, et ultricies turpis imperdiet. Sed suscipit pellentesque facilisis. Sed ut consequat ante Suspendisse suscipit sodales metus. Mauris ac nisi sed ex malesuada tempus. Praesent sit amet congue nibh, eu molestie mauris. Ut ut viverra lorem. Donec pulvinar elit ut orci ultrices, id feugiat leo sollicitudin. Donec eleifend aliquam volutpat. Nulla ultrices nunc eu lectus blandit, sed tincidunt nulla porttitor. Quisque nec ornare erat. Aenean gravida nunc non facilisis molestie. Nam at est arcu. Suspendisse lobortis metus non nulla fermentum mollis. Proin ultrices mi lacus, a efficitur ipsum suscipit eget.",
      imageUrl: "/asset/image/sample/sample15.jpg",
    },
    {
      id: "6",
      title: "Meet The Women Behind New York’s Coolest Design Shop",
      category: "Design",
      time: "June 09, 2022",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id urna et justo mattis tincidunt. Maecenas consectetur quam in nibh sollicitudin ultricies. Vestibulum ac nunc nunc. Pellentesque auctor massa ac leo mollis pretium a vel ligula. Sed gravida dictum massa, at rhoncus urna fringilla in. Duis orci nibh, iaculis nec finibus vitae, sagittis eget libero. Vestibulum sed placerat turpis. Nunc nec orci vel felis tempor rutrum aliquam eu orci. Proin euismod efficitur magna. Quisque pharetra purus tortor, laoreet pellentesque ligula blandit in. Pellentesque id commodo urna. Curabitur varius tellus nisl, non vestibulum odio tincidunt sed. Praesent non mauris a diam finibus porta. Mauris ac dapibus sapien. Maecenas imperdiet eros quis quam tempor, et tincidunt nibh suscipit. Praesent sit amet imperdiet est, eget pellentesque libero. Vestibulum in mollis ipsum, non ultricies ex. Vivamus porttitor sodales eros id gravida. Vestibulum ante orci, vulputate vitae tempus non, sollicitudin ut nibh. Mauris sed risus risus. Ut feugiat dui at lobortis molestie. Integer efficitur luctus ligula nec condimentum. Etiam ultrices, massa sed dignissim gravida, sapien neque cursus lectus, in tristique dui enim eu tellus. Aenean eu rhoncus felis, in commodo justo. Aenean vel diam faucibus, ornare libero eget, porttitor felis. Mauris eu sapien eros. Donec rhoncus molestie malesuada. Nullam ut lectus elit. Proin mollis turpis eu condimentum condimentum. Phasellus eget tincidunt arcu. Curabitur ornare semper dui. Fusce facilisis euismod enim ac ultrices. Mauris efficitur velit ac urna hendrerit, eu aliquet enim ullamcorper. Ut rhoncus volutpat tincidunt. Suspendisse non sapien sodales ipsum commodo congue at in nunc. Etiam ut metus a est malesuada lacinia vitae quis est. Quisque ullamcorper felis sit amet molestie consequat. In vel dapibus elit. Duis non neque in augue sagittis molestie Pellentesque felis lectus, tincidunt id diam quis, mollis tempor neque. Ut id pharetra nibh, a porta lacus. Nunc pretium sapien a arcu facilisis, tincidunt interdum nulla ullamcorper. Aliquam mattis ante nibh, at aliquet est dignissim et. Sed sit amet leo ut risus semper convallis. In aliquet nunc ac quam bibendum, et ultricies turpis imperdiet. Sed suscipit pellentesque facilisis. Sed ut consequat ante Suspendisse suscipit sodales metus. Mauris ac nisi sed ex malesuada tempus. Praesent sit amet congue nibh, eu molestie mauris. Ut ut viverra lorem. Donec pulvinar elit ut orci ultrices, id feugiat leo sollicitudin. Donec eleifend aliquam volutpat. Nulla ultrices nunc eu lectus blandit, sed tincidunt nulla porttitor. Quisque nec ornare erat. Aenean gravida nunc non facilisis molestie. Nam at est arcu. Suspendisse lobortis metus non nulla fermentum mollis. Proin ultrices mi lacus, a efficitur ipsum suscipit eget.",
      imageUrl: "/asset/image/sample/sample21.jpg",
    },
    {
      id: "7",
      title: "The New Autumn Denim Guide: The Best Gift For Stylish Women",
      category: "Coding",
      time: "June 06, 2022",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id urna et justo mattis tincidunt. Maecenas consectetur quam in nibh sollicitudin ultricies. Vestibulum ac nunc nunc. Pellentesque auctor massa ac leo mollis pretium a vel ligula. Sed gravida dictum massa, at rhoncus urna fringilla in. Duis orci nibh, iaculis nec finibus vitae, sagittis eget libero. Vestibulum sed placerat turpis. Nunc nec orci vel felis tempor rutrum aliquam eu orci. Proin euismod efficitur magna. Quisque pharetra purus tortor, laoreet pellentesque ligula blandit in. Pellentesque id commodo urna. Curabitur varius tellus nisl, non vestibulum odio tincidunt sed. Praesent non mauris a diam finibus porta. Mauris ac dapibus sapien. Maecenas imperdiet eros quis quam tempor, et tincidunt nibh suscipit. Praesent sit amet imperdiet est, eget pellentesque libero. Vestibulum in mollis ipsum, non ultricies ex. Vivamus porttitor sodales eros id gravida. Vestibulum ante orci, vulputate vitae tempus non, sollicitudin ut nibh. Mauris sed risus risus. Ut feugiat dui at lobortis molestie. Integer efficitur luctus ligula nec condimentum. Etiam ultrices, massa sed dignissim gravida, sapien neque cursus lectus, in tristique dui enim eu tellus. Aenean eu rhoncus felis, in commodo justo. Aenean vel diam faucibus, ornare libero eget, porttitor felis. Mauris eu sapien eros. Donec rhoncus molestie malesuada. Nullam ut lectus elit. Proin mollis turpis eu condimentum condimentum. Phasellus eget tincidunt arcu. Curabitur ornare semper dui. Fusce facilisis euismod enim ac ultrices. Mauris efficitur velit ac urna hendrerit, eu aliquet enim ullamcorper. Ut rhoncus volutpat tincidunt. Suspendisse non sapien sodales ipsum commodo congue at in nunc. Etiam ut metus a est malesuada lacinia vitae quis est. Quisque ullamcorper felis sit amet molestie consequat. In vel dapibus elit. Duis non neque in augue sagittis molestie Pellentesque felis lectus, tincidunt id diam quis, mollis tempor neque. Ut id pharetra nibh, a porta lacus. Nunc pretium sapien a arcu facilisis, tincidunt interdum nulla ullamcorper. Aliquam mattis ante nibh, at aliquet est dignissim et. Sed sit amet leo ut risus semper convallis. In aliquet nunc ac quam bibendum, et ultricies turpis imperdiet. Sed suscipit pellentesque facilisis. Sed ut consequat ante Suspendisse suscipit sodales metus. Mauris ac nisi sed ex malesuada tempus. Praesent sit amet congue nibh, eu molestie mauris. Ut ut viverra lorem. Donec pulvinar elit ut orci ultrices, id feugiat leo sollicitudin. Donec eleifend aliquam volutpat. Nulla ultrices nunc eu lectus blandit, sed tincidunt nulla porttitor. Quisque nec ornare erat. Aenean gravida nunc non facilisis molestie. Nam at est arcu. Suspendisse lobortis metus non nulla fermentum mollis. Proin ultrices mi lacus, a efficitur ipsum suscipit eget.",
      imageUrl: "/asset/image/sample/sample19.jpg",
    },
    {
      id: "8",
      title: "Meet The Women Behind New York’s Coolest Design Shop",
      category: "Design",
      time: "June 09, 2022",
      content:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer id urna et justo mattis tincidunt. Maecenas consectetur quam in nibh sollicitudin ultricies. Vestibulum ac nunc nunc. Pellentesque auctor massa ac leo mollis pretium a vel ligula. Sed gravida dictum massa, at rhoncus urna fringilla in. Duis orci nibh, iaculis nec finibus vitae, sagittis eget libero. Vestibulum sed placerat turpis. Nunc nec orci vel felis tempor rutrum aliquam eu orci. Proin euismod efficitur magna. Quisque pharetra purus tortor, laoreet pellentesque ligula blandit in. Pellentesque id commodo urna. Curabitur varius tellus nisl, non vestibulum odio tincidunt sed. Praesent non mauris a diam finibus porta. Mauris ac dapibus sapien. Maecenas imperdiet eros quis quam tempor, et tincidunt nibh suscipit. Praesent sit amet imperdiet est, eget pellentesque libero. Vestibulum in mollis ipsum, non ultricies ex. Vivamus porttitor sodales eros id gravida. Vestibulum ante orci, vulputate vitae tempus non, sollicitudin ut nibh. Mauris sed risus risus. Ut feugiat dui at lobortis molestie. Integer efficitur luctus ligula nec condimentum. Etiam ultrices, massa sed dignissim gravida, sapien neque cursus lectus, in tristique dui enim eu tellus. Aenean eu rhoncus felis, in commodo justo. Aenean vel diam faucibus, ornare libero eget, porttitor felis. Mauris eu sapien eros. Donec rhoncus molestie malesuada. Nullam ut lectus elit. Proin mollis turpis eu condimentum condimentum. Phasellus eget tincidunt arcu. Curabitur ornare semper dui. Fusce facilisis euismod enim ac ultrices. Mauris efficitur velit ac urna hendrerit, eu aliquet enim ullamcorper. Ut rhoncus volutpat tincidunt. Suspendisse non sapien sodales ipsum commodo congue at in nunc. Etiam ut metus a est malesuada lacinia vitae quis est. Quisque ullamcorper felis sit amet molestie consequat. In vel dapibus elit. Duis non neque in augue sagittis molestie Pellentesque felis lectus, tincidunt id diam quis, mollis tempor neque. Ut id pharetra nibh, a porta lacus. Nunc pretium sapien a arcu facilisis, tincidunt interdum nulla ullamcorper. Aliquam mattis ante nibh, at aliquet est dignissim et. Sed sit amet leo ut risus semper convallis. In aliquet nunc ac quam bibendum, et ultricies turpis imperdiet. Sed suscipit pellentesque facilisis. Sed ut consequat ante Suspendisse suscipit sodales metus. Mauris ac nisi sed ex malesuada tempus. Praesent sit amet congue nibh, eu molestie mauris. Ut ut viverra lorem. Donec pulvinar elit ut orci ultrices, id feugiat leo sollicitudin. Donec eleifend aliquam volutpat. Nulla ultrices nunc eu lectus blandit, sed tincidunt nulla porttitor. Quisque nec ornare erat. Aenean gravida nunc non facilisis molestie. Nam at est arcu. Suspendisse lobortis metus non nulla fermentum mollis. Proin ultrices mi lacus, a efficitur ipsum suscipit eget.",
      imageUrl: "/asset/image/sample/sample22.jpg",
    },
  ];
  return (
    <Layout>
      <section className="mx-auto max-w-screen-xs md:max-w-screen-sm lg:max-w-screen-xl xl:max-w-screen-2xl grid">
        {/* <div className="card-container grid lg:grid-cols-4"> */}
        <div className="columns-1 md:columns-2 lg:columns-4 space-x-6">
          {blogs.map((blog) => (
            <div
              className="card mb-8 w-72 text-center space-y-4 py-8"
              key={blog.id}
            >
              <figure className="w-72 h-full relative mb-4 ">
                <Image
                  src={blog.imageUrl}
                  width={300}
                  height={400}
                  // layout="fill"
                  className=" object-contain"
                  alt="."
                ></Image>
              </figure>
              <h4 className="card__subtitle text-sky-500">{blog.category}</h4>
              <h2 className="card__title">{blog.title}</h2>
              <div className="flex justify-center pb-4">
                <hr className="divider--sm w-8" />
              </div>
              <time>{blog.time}</time>
            </div>
          ))}
        </div>
      </section>
    </Layout>
  );
}
